"""
prompt_test.py
Compare YOLOE detection quality across prompts generated by different LLMs.

Loads prompt banks from:
    datasets/prompt/<dataset>/<object_folder>.json

Measures per prompt:  YOLOE confidence, mask size, IoU vs GT mask.
Ranks LLMs by:        detection rate, mean confidence, best confidence.

Usage:
    # Test all DexYCB objects using pre-generated prompt banks
    python pipeline/prompt_test.py --dataset dexycb

    # Test one object only
    python pipeline/prompt_test.py --dataset dexycb --obj 006_mustard_bottle

    # Auto-generate LLaMA prompt banks first (calls Ollama), then test
    python pipeline/prompt_test.py --dataset dexycb --generate llama

    # Generate + test all at once
    python pipeline/prompt_test.py --dataset dexycb --generate llama --run
"""

import os
import sys
import json
import argparse
import numpy as np
import cv2

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

BASE_DIR = os.path.expanduser('~/open-vocabulary-6d-pose-yoloe')
sys.path.insert(0, os.path.join(BASE_DIR, 'utils'))
sys.path.insert(0, os.path.join(BASE_DIR, 'pipeline'))

from set_config       import DATASETS, EVAL_DIR, YOLOE_CONF, YOLOE_IOU, YOLOE_MODEL_PATH
from pipeline_utils   import compute_mask_metrics
from yoloe_helpers    import yoloe_text_prompt
from ollama_utils     import is_ollama_running

PROMPT_DIR = os.path.join(BASE_DIR, 'datasets', 'prompt')
OLLAMA_HOST = 'http://localhost:11434'

LLM_COLORS = {
    'llama'          : '#1565C0',
    'chatgpt'        : '#2E7D32',
    'claude'         : '#F57F17',
    'deepseek'       : '#6A1B9A',
    'pose_extractor' : '#AD1457',
    'manual'         : '#37474F',
    'systematic'     : '#00838F',
}


# ── Prompt bank I/O ───────────────────────────────────────────────────────────

def _prompt_bank_path(dataset, folder):
    return os.path.join(PROMPT_DIR, dataset, f'{folder}.json')


def load_prompt_bank(dataset, folder):
    """
    Load prompt banks from JSON.  Returns dict {llm_name: [prompts]}.
    Returns {} if file does not exist.
    """
    path = _prompt_bank_path(dataset, folder)
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        data = json.load(f)
    return data.get('prompts', {})


def save_prompt_bank(dataset, folder, banks, metadata=None):
    """Save or merge prompt banks into JSON."""
    path = _prompt_bank_path(dataset, folder)
    os.makedirs(os.path.dirname(path), exist_ok=True)

    existing = {}
    if os.path.exists(path):
        with open(path) as f:
            existing = json.load(f)

    existing.setdefault('object',  folder)
    existing.setdefault('dataset', dataset)
    existing.setdefault('prompts', {})
    existing['prompts'].update(banks)
    if metadata:
        existing.setdefault('metadata', {}).update(metadata)

    with open(path, 'w') as f:
        json.dump(existing, f, indent=2)
    print(f'  Saved: {path}')


# ── LLaMA bank generation (via Ollama) ───────────────────────────────────────

def generate_llama_bank(base_prompt, n=30, model='llama3.2:3b'):
    """Call Ollama to get n diverse YOLOE prompts for base_prompt."""
    import requests, ast

    if not is_ollama_running():
        raise RuntimeError('Ollama is not running.  Start with: ollama serve')

    system = (
        f'Generate a Python list of {n} diverse text prompts for YOLOE open-vocabulary '
        f'object detection. Object: "{base_prompt}". '
        f'Vary: color, material, brand, shape, function. '
        f'Each prompt 1-6 words. Return ONLY a valid Python list of strings.'
    )
    payload = {
        'model'  : model,
        'prompt' : system,
        'stream' : False,
        'keep_alive': 0,
        'options': {'temperature': 0.4, 'num_predict': 600},
    }
    r = requests.post(f'{OLLAMA_HOST}/api/generate', json=payload, timeout=60)
    r.raise_for_status()
    raw   = r.json()['response'].strip()
    start = raw.find('[')
    end   = raw.rfind(']') + 1
    if 0 <= start < end:
        # join across newlines so ast.literal_eval handles multi-line lists
        list_str = ' '.join(raw[start:end].splitlines())
        try:
            prompts = [str(p).strip().lower()
                       for p in ast.literal_eval(list_str) if str(p).strip()]
            return prompts[:n]
        except Exception:
            pass
    # fallback: extract quoted strings with regex
    import re
    prompts = [m.group(1).strip().lower()
               for m in re.finditer(r'["\']([^"\']{3,60})["\']', raw)]
    prompts = list(dict.fromkeys(prompts))   # deduplicate preserving order
    if prompts:
        return prompts[:n]
    raise ValueError(f'Could not parse Ollama response: {raw[:200]}')


def generate_systematic_bank(base_prompt):
    """Systematic variations without any LLM (always available)."""
    words    = base_prompt.strip().lower().split()
    core     = words[-1]
    adj      = words[0] if len(words) > 1 else ''
    COLORS   = ['yellow','red','blue','green','white','orange','brown','black','grey']
    MATS     = ['plastic','metal','glass','cardboard','rubber','ceramic','wooden']
    SIZES    = ['small','large','big','medium','tiny','compact']
    pool     = {base_prompt, core, f'a {base_prompt}', f'the {base_prompt}'}
    for c in COLORS: pool.add(f'{c} {core}')
    for m in MATS:   pool.add(f'{m} {core}')
    for s in SIZES:  pool.add(f'{s} {core}')
    if adj:
        for m in MATS[:3]: pool.add(f'{adj} {m} {core}')
    return sorted(p for p in pool if p.strip())


# ── YOLOE testing ─────────────────────────────────────────────────────────────

def test_prompt_list(yoloe_model, image_path, prompts,
                     conf=YOLOE_CONF, iou=YOLOE_IOU, gt_mask=None):
    """
    Test each prompt with YOLOE.  Returns list of result dicts.
    """
    results = []
    for prompt in prompts:
        try:
            _, mask, det_conf, _ = yoloe_text_prompt(
                yoloe_model, image_path, prompt, conf=conf, iou=iou
            )
            iou_score = 0.0
            if gt_mask is not None and mask is not None:
                iou_score = compute_mask_metrics(mask, gt_mask)['IoU']
            results.append({
                'prompt'   : prompt,
                'conf'     : float(det_conf),
                'mask_px'  : int(mask.sum()) if mask is not None else 0,
                'iou_score': iou_score,
                'detected' : True,
            })
        except Exception:
            results.append({
                'prompt'   : prompt,
                'conf'     : 0.0,
                'mask_px'  : 0,
                'iou_score': 0.0,
                'detected' : False,
            })
    return results


def aggregate_llm_stats(prompt_results):
    """Compute summary stats for one LLM's prompt list."""
    detected = [r for r in prompt_results if r['detected']]
    confs    = [r['conf']      for r in detected]
    ious     = [r['iou_score'] for r in detected]
    best     = max(prompt_results, key=lambda x: x['conf'])
    return {
        'n_prompts'     : len(prompt_results),
        'n_detected'    : len(detected),
        'det_rate'      : len(detected) / max(len(prompt_results), 1),
        'mean_conf'     : float(np.mean(confs)) if confs else 0.0,
        'best_conf'     : float(best['conf']),
        'best_prompt'   : best['prompt'],
        'mean_iou'      : float(np.mean(ious))  if ious  else 0.0,
    }


# ── Visualization ─────────────────────────────────────────────────────────────

def save_comparison_fig(stats_by_llm, obj_name, out_path):
    """
    3-panel comparison: detection rate | mean confidence | best confidence.
    One bar per LLM.
    """
    llms   = list(stats_by_llm.keys())
    colors = [LLM_COLORS.get(l, '#90A4AE') for l in llms]

    det_rates   = [stats_by_llm[l]['det_rate']   * 100 for l in llms]
    mean_confs  = [stats_by_llm[l]['mean_conf']         for l in llms]
    best_confs  = [stats_by_llm[l]['best_conf']         for l in llms]

    fig, axes = plt.subplots(1, 3, figsize=(13, 4))
    fig.patch.set_facecolor('#fafafa')

    def _bar(ax, vals, title, ylabel, ylim=None):
        bars = ax.bar(range(len(llms)), vals, color=colors, width=0.55, edgecolor='none')
        ax.set_xticks(range(len(llms)))
        ax.set_xticklabels(llms, fontsize=9, rotation=20, ha='right')
        ax.set_title(title, fontsize=10, pad=6)
        ax.set_ylabel(ylabel, fontsize=9)
        if ylim:
            ax.set_ylim(0, ylim)
        ax.grid(axis='y', alpha=0.3)
        ax.spines[['top','right']].set_visible(False)
        for bar, val in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width()/2,
                    bar.get_height() + (ylim or 1) * 0.02,
                    f'{val:.1f}{"%" if "Rate" in title else ""}',
                    ha='center', va='bottom', fontsize=8)

    _bar(axes[0], det_rates,  'Detection Rate (%)', '%',          ylim=110)
    _bar(axes[1], mean_confs, 'Mean Confidence',    'Confidence', ylim=1.05)
    _bar(axes[2], best_confs, 'Best Confidence',    'Confidence', ylim=1.05)

    plt.suptitle(
        f'{obj_name.replace("_"," ")} — LLM Prompt Comparison',
        fontsize=11, y=1.02
    )
    plt.tight_layout()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    fig.savefig(out_path, dpi=120, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f'  Comparison fig: {out_path}')


def save_per_llm_ranking_fig(all_results_by_llm, obj_name, out_path, top_n=20):
    """
    Horizontal bar chart: top top_n prompts for each LLM side by side.
    """
    llms   = list(all_results_by_llm.keys())
    n_llms = len(llms)
    if n_llms == 0:
        return

    fig, axes = plt.subplots(1, n_llms, figsize=(6 * n_llms, max(5, top_n * 0.25)))
    if n_llms == 1:
        axes = [axes]

    for ax, llm in zip(axes, llms):
        results  = all_results_by_llm[llm]
        top      = sorted(results, key=lambda x: x['conf'], reverse=True)[:top_n]
        labels   = [r['prompt'][:28] for r in top]
        confs    = [r['conf']        for r in top]
        cols     = ['#43A047' if r['detected'] else '#EF5350' for r in top]

        ax.barh(range(len(top)), confs, color=cols, height=0.65)
        ax.set_yticks(range(len(top)))
        ax.set_yticklabels(labels, fontsize=7)
        ax.invert_yaxis()
        ax.set_xlabel('Confidence', fontsize=8)
        ax.set_title(llm.upper(), fontsize=9,
                     color=LLM_COLORS.get(llm,'#333333'), fontweight='bold')
        ax.set_xlim(0, 1.05)
        ax.axvline(YOLOE_CONF, color='grey', linestyle='--', linewidth=0.7)
        ax.grid(axis='x', alpha=0.25)
        ax.spines[['top','right']].set_visible(False)

    plt.suptitle(f'{obj_name.replace("_"," ")} — Top prompts per LLM', fontsize=10)
    plt.tight_layout()
    fig.savefig(out_path, dpi=120, bbox_inches='tight')
    plt.close(fig)
    print(f'  Per-LLM ranking: {out_path}')


# ── Terminal output ───────────────────────────────────────────────────────────

def print_comparison(stats_by_llm, obj_name):
    print(f'\n  Object: {obj_name}')
    hdr = f'  {"LLM":<12} {"N":>4} {"Det%":>6} {"MeanConf":>9} {"BestConf":>9} {"MeanIoU":>8} {"Best prompt"}'
    print(hdr)
    print('  ' + '─' * 80)
    ranked = sorted(stats_by_llm.items(), key=lambda x: x[1]['best_conf'], reverse=True)
    for llm, s in ranked:
        print(
            f'  {llm:<12} {s["n_prompts"]:>4} '
            f'{s["det_rate"]*100:>5.1f}% '
            f'{s["mean_conf"]:>9.3f} '
            f'{s["best_conf"]:>9.3f} '
            f'{s["mean_iou"]:>8.3f} '
            f'"{s["best_prompt"][:35]}"'
        )


# ── Excel export ──────────────────────────────────────────────────────────────

def export_comparison_excel(all_obj_stats, dataset_name, out_path):
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils import get_column_letter
    except ImportError:
        print('  openpyxl not found — skip Excel')
        return

    wb   = openpyxl.Workbook()
    thin = Border(**{s: Side(style='thin') for s in ('left','right','top','bottom')})

    for obj_name, stats_by_llm in all_obj_stats.items():
        ws = wb.create_sheet(title=obj_name[:20])
        headers = ['LLM', 'N prompts', 'N detected', 'Det rate',
                   'Mean conf', 'Best conf', 'Mean IoU', 'Best prompt']
        ws.append(headers)
        h_fill = PatternFill(start_color='37474F', end_color='37474F', fill_type='solid')
        for c in range(1, len(headers)+1):
            cell = ws.cell(1, c)
            cell.fill = h_fill
            cell.font = Font(color='FFFFFF', bold=True, size=9)
            cell.alignment = Alignment(horizontal='center')
            cell.border = thin

        ranked = sorted(stats_by_llm.items(), key=lambda x: x[1]['best_conf'], reverse=True)
        for i, (llm, s) in enumerate(ranked, 1):
            row = [
                llm,
                s['n_prompts'],
                s['n_detected'],
                round(s['det_rate'], 3),
                round(s['mean_conf'], 4),
                round(s['best_conf'], 4),
                round(s['mean_iou'],  4),
                s['best_prompt'],
            ]
            ws.append(row)
            cur = ws.max_row
            for c in range(1, len(headers)+1):
                ws.cell(cur, c).border = thin

            # highlight best row (rank 1) in light blue
            if i == 1:
                hl = PatternFill(start_color='BBDEFB', end_color='BBDEFB', fill_type='solid')
                for c in range(1, len(headers)+1):
                    ws.cell(cur, c).fill = hl

        for ci, w in enumerate([12, 10, 11, 9, 10, 10, 9, 40], 1):
            ws.column_dimensions[get_column_letter(ci)].width = w

    if 'Sheet' in wb.sheetnames:
        del wb['Sheet']

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    wb.save(out_path)
    print(f'  Excel: {out_path}')


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='Compare LLM prompts on YOLOE detection'
    )
    parser.add_argument('--dataset',  default='dexycb')
    parser.add_argument('--obj',      default=None)
    parser.add_argument('--generate', default=None,
                        help='Generate prompt banks for this LLM. '
                             'Supported: llama  (calls Ollama)')
    parser.add_argument('--n',        type=int, default=30,
                        help='Prompts to generate per object')
    parser.add_argument('--run',      action='store_true',
                        help='Run YOLOE evaluation after generating banks')
    parser.add_argument('--conf',     type=float, default=YOLOE_CONF)
    parser.add_argument('--iou',      type=float, default=YOLOE_IOU)
    parser.add_argument('--ollama-model', default='llama3.2:3b')
    args = parser.parse_args()

    if args.dataset not in DATASETS:
        print(f'Unknown dataset. Available: {list(DATASETS.keys())}')
        sys.exit(1)

    dataset_cfg = DATASETS[args.dataset]
    objects     = dataset_cfg['objects']
    if not objects:
        print(f'No objects configured for "{args.dataset}".')
        sys.exit(0)

    if args.obj:
        objects = [o for o in objects if o['folder'] == args.obj]
        if not objects:
            print(f'Object "{args.obj}" not found.')
            sys.exit(1)

    # ── Generate mode ──────────────────────────────────────────────────────────
    if args.generate:
        llm = args.generate.lower()
        print(f'\nGenerating {llm} prompt banks for {args.dataset}...')

        for obj_cfg in objects:
            folder = obj_cfg['folder']
            base   = obj_cfg['prompt'] if isinstance(obj_cfg['prompt'], str) \
                     else obj_cfg['prompt'][0]
            print(f'\n  [{folder}]  base="{base}"')

            if llm == 'llama':
                prompts  = generate_llama_bank(base, n=args.n, model=args.ollama_model)
                sys_bank = generate_systematic_bank(base)
                banks    = {'llama': prompts, 'systematic': sys_bank}
                meta     = {'llama': {'model': args.ollama_model, 'n': len(prompts)},
                            'systematic': {'model': 'rule-based', 'n': len(sys_bank)}}
            else:
                print(f'  LLM "{llm}" must be added manually. See datasets/prompt/README.md')
                continue

            save_prompt_bank(args.dataset, folder, banks, meta)

        if not args.run:
            print('\nDone. Run with --run to test with YOLOE.')
            return

    # ── Evaluation mode ────────────────────────────────────────────────────────
    print(f'\nLoading YOLOE model...')
    from ultralytics import YOLOE
    yoloe_model = YOLOE(YOLOE_MODEL_PATH)
    yoloe_model.to('cuda')

    viz_dir = os.path.join(EVAL_DIR, args.dataset, 'prompt_test')
    os.makedirs(viz_dir, exist_ok=True)

    all_obj_stats = {}
    SEP = '═' * 85

    print(f'\n{SEP}')
    print(f'  LLM PROMPT COMPARISON — {dataset_cfg["name"]}')
    print(SEP)

    for obj_cfg in objects:
        folder     = obj_cfg['folder']
        anchor_dir = os.path.join(dataset_cfg['anchor_dir'], folder)
        color_path = os.path.join(anchor_dir, 'color.png')
        gt_mask_p  = os.path.join(anchor_dir, 'mask.png')

        if not os.path.exists(color_path):
            print(f'  [skip] {folder}: color.png not found')
            continue

        gt_mask = None
        if os.path.exists(gt_mask_p):
            gm = cv2.imread(gt_mask_p, cv2.IMREAD_GRAYSCALE)
            gt_mask = gm > 127

        banks = load_prompt_bank(args.dataset, folder)
        if not banks:
            print(f'  [skip] {folder}: no prompt bank at '
                  f'{_prompt_bank_path(args.dataset, folder)}\n'
                  f'         Run: python pipeline/prompt_test.py '
                  f'--dataset {args.dataset} --generate llama')
            continue

        stats_by_llm      = {}
        results_by_llm    = {}
        print(f'\n  [{folder}]  testing {sum(len(v) for v in banks.values())} prompts '
              f'across {len(banks)} LLMs...')

        for llm_name, prompts in banks.items():
            if not prompts:
                continue
            pr = test_prompt_list(yoloe_model, color_path, prompts,
                                  conf=args.conf, iou=args.iou, gt_mask=gt_mask)
            stats_by_llm[llm_name]   = aggregate_llm_stats(pr)
            results_by_llm[llm_name] = pr

        if not stats_by_llm:
            continue

        print_comparison(stats_by_llm, folder)
        all_obj_stats[folder] = stats_by_llm

        obj_viz = os.path.join(viz_dir, folder)
        os.makedirs(obj_viz, exist_ok=True)

        save_comparison_fig(
            stats_by_llm, folder,
            os.path.join(obj_viz, 'llm_comparison.png')
        )
        save_per_llm_ranking_fig(
            results_by_llm, folder,
            os.path.join(obj_viz, 'per_llm_ranking.png')
        )

    if all_obj_stats:
        excel_path = os.path.join(EVAL_DIR, args.dataset,
                                  f'{args.dataset}_prompt_comparison.xlsx')
        export_comparison_excel(all_obj_stats, dataset_cfg['name'], excel_path)

    print(f'\n{SEP}')
    print(f'  Results saved to: {viz_dir}')
    print(SEP + '\n')


if __name__ == '__main__':
    main()
